<!--                <tr>-->
<!--                    <td class="col-sm-2">-->
<!--                        <div class="form-group">-->
<!--                            <label>Select 1</label>-->
<!--                            <select v-model="fields.val_1" class="form-control" :disabled="disable">-->
<!--                                <option value="rdl_1">D101A-L</option>-->
<!--                                <option value="rdl_2">D101B-L</option>-->
<!--                                <option value="rdl_3">D405A-L</option>-->
<!--                                <option value="rdl_4">D405B-L</option>-->
<!--                                <option value="rdl_5">D405C-L</option>-->
<!--                                <option value="rdl_6">C401A-L</option>-->
<!--                                <option value="rdl_7">C401B-L</option>-->
<!--                                <option value="rdl_8">D402A-L</option>-->
<!--                                <option value="rdl_9">D402B-L</option>-->
<!--                                <option value="rdl_10">D402C-L</option>-->
<!--                                <option value="rdl_11">D402D-L</option>-->
<!--                                <option value="rdl_12">GLV-L</option>-->
<!--                                <option value="rdl_13">SettlingA-L</option>-->
<!--                                <option value="rdl_14">SettlingB-L</option>-->
<!--                                <option value="rdl_15">SettlingC-L</option>-->
<!--                                <option value="rdl_16">Methanol T1-L</option>-->
<!--                                <option value="rdl_17">Tar-L</option>-->
<!--                                <option value="rdl_18">GST T1-L</option>-->
<!--                                <option value="rdl_19">Methanol T2-L</option>-->
<!--                                <option value="rdl_20">SP1-L</option>-->
<!--                                <option value="rdl_21">SP2-L</option>-->
<!--                                <option value="rdl_22">SP3-L</option>-->
<!--                                <option value="rdl_23">PPRA-L</option>-->
<!--                                <option value="rdl_24">PPRB-L</option>-->
<!--                                <option value="rdl_25">H2SO4-L</option>-->
<!--                                <option value="rtd_1">E101-T</option>-->
<!--                                <option value="rtd_2">D101A-T</option>-->
<!--                                <option value="rtd_3">D101B-T</option>-->
<!--                                <option value="rtd_4">E201-T</option>-->
<!--                                <option value="rtd_5">GLV-Top-T</option>-->
<!--                                <option value="rtd_6">GLV-Mid-T</option>-->
<!--                                <option value="rtd_7">GLV-BTM-T</option>-->
<!--                                <option value="rtd_8">GLV-EVP-T</option>-->
<!--                                <option value="rtd_9">SettlingA-T</option>-->
<!--                                <option value="rtd_10">SettlingB-T</option>-->
<!--                                <option value="rtd_11">SettlingC-T</option>-->
<!--                                <option value="rtd_12">HotWater-T</option>-->
<!--                                <option value="rtd_13">D402A-T</option>-->
<!--                                <option value="rtd_14">D402B-T</option>-->
<!--                                <option value="rtd_15">D402C-T</option>-->
<!--                                <option value="rtd_16">D402D-T</option>-->
<!--                                <option value="rtd_17">Trans-EVP-T</option>-->
<!--                                <option value="rtd_18">Blue-T</option>-->
<!--                                <option value="rtd_19">Green-T</option>-->
<!--                                <option value="rtd_20">Old Green-T</option>-->
<!--                                <option value="rtd_21">E601-T</option>-->
<!--                                <option value="rtd_22">T601-Top-T</option>-->
<!--                                <option value="rtd_23">T601-Mid-T</option>-->
<!--                                <option value="rtd_24">T601-BTM-T</option>-->
<!--                                <option value="rtd_25">E501-T</option>-->
<!--                                <option value="rtd_26">D501-T</option>-->
<!--                                <option value="rtd_27">T501-Top-T</option>-->
<!--                                <option value="rtd_28">T501-Mid-T</option>-->
<!--                                <option value="rtd_29">T501-BTM-T</option>-->
<!--                                <option value="rtd_30">T502-Mid-T</option>-->
<!--                                <option value="rtd_31">T502-BTM-T</option>-->
<!--&lt;!&ndash;                                <option value="rtd_32">PPRA-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_33">PPRB-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_34">GST-T1-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_35">Trans-React-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_36">Bio Storage-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_37">Bio Transfer-T</option>&ndash;&gt;-->
<!--                                <option value="dpl_1">D501-L</option>-->
<!--                                <option value="dpl_2">E401-L</option>-->
<!--                                <option value="dpl_3">T601-L</option>-->
<!--                                <option value="dpl_4">D503-L</option>-->
<!--                                <option value="dpl_5">D504-L</option>-->
<!--                                <option value="dpl_6">T501-L</option>-->
<!--                                <option value="dpl_7">T502-L</option>-->
<!--                                <option value="fm_1">FM 1</option>-->
<!--                                <option value="fm_2">FM 2</option>-->
<!--                                <option value="fm_3">FM 3</option>-->
<!--                                <option value="fm_4">FM 4</option>-->
<!--                                <option value="fm_5">FM 5</option>-->
<!--                                <option value="fm_6">FM 6</option>-->
<!--                                <option value="fm_7">FM 7</option>-->
<!--                                <option value="fm_8">FM 8</option>-->
<!--                                <option value="fm_9">FM 9</option>-->
<!--                                <option value="fm_10">FM 10</option>-->
<!--                                <option value="fm_11">FM 11</option>-->
<!--                                <option value="fm_12">FM 12</option>-->
<!--                                <option value="fm_13">FM 13</option>-->
<!--                                <option value="fm_14">FM 14</option>-->
<!--                                <option value="fm_15">FM 15</option>-->
<!--                                <option value="fm_16">FM 16</option>-->
<!--                                <option value="fm_17">FM 17</option>-->
<!--                                <option value="fm_18">FM 18</option>-->
<!--                                <option value="fm_19">FM 19</option>-->
<!--                                <option value="fm_20">FM 20</option>-->
<!--                                <option value="fm_21">FM 21</option>-->
<!--                                <option value="fm_22">FM 22</option>-->
<!--                                <option value="fm_23">FM 23</option>-->
<!--                                <option value="fm_24">FM 24</option>-->
<!--                                <option value="fm_25">FM 25</option>-->
<!--                                <option value="fm_26">FM 26</option>-->
<!--                                <option value="fm_27">FM 27</option>-->
<!--                                <option value="pt_1">PT 1</option>-->
<!--                                <option value="pt_2">PT 2</option>-->
<!--                                <option value="pt_3">PT 3</option>-->
<!--                                <option value="pt_4">PT 4</option>-->
<!--                                <option value="pt_5">PT 5</option>-->
<!--                                <option value="vg_1">VG 1</option>-->
<!--                                <option value="vg_2">VG 2</option>-->
<!--                                <option value="vg_3">VG 3</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                    </td>-->
<!--                    <td class="col-sm-2">-->
<!--                        <div class="form-group">-->
<!--                            <label>Select 2</label>-->
<!--                            <select v-model="fields.val_2" class="form-control" :disabled="disable">-->
<!--                                <option value="rdl_1">D101A-L</option>-->
<!--                                <option value="rdl_2">D101B-L</option>-->
<!--                                <option value="rdl_3">D405A-L</option>-->
<!--                                <option value="rdl_4">D405B-L</option>-->
<!--                                <option value="rdl_5">D405C-L</option>-->
<!--                                <option value="rdl_6">C401A-L</option>-->
<!--                                <option value="rdl_7">C401B-L</option>-->
<!--                                <option value="rdl_8">D402A-L</option>-->
<!--                                <option value="rdl_9">D402B-L</option>-->
<!--                                <option value="rdl_10">D402C-L</option>-->
<!--                                <option value="rdl_11">D402D-L</option>-->
<!--                                <option value="rdl_12">GLV-L</option>-->
<!--                                <option value="rdl_13">SettlingA-L</option>-->
<!--                                <option value="rdl_14">SettlingB-L</option>-->
<!--                                <option value="rdl_15">SettlingC-L</option>-->
<!--                                <option value="rdl_16">Methanol T1-L</option>-->
<!--                                <option value="rdl_17">Tar-L</option>-->
<!--                                <option value="rdl_18">GST T1-L</option>-->
<!--                                <option value="rdl_19">Methanol T2-L</option>-->
<!--                                <option value="rdl_20">SP1-L</option>-->
<!--                                <option value="rdl_21">SP2-L</option>-->
<!--                                <option value="rdl_22">SP3-L</option>-->
<!--                                <option value="rdl_23">PPRA-L</option>-->
<!--                                <option value="rdl_24">PPRB-L</option>-->
<!--                                <option value="rdl_25">H2SO4-L</option>-->
<!--                                <option value="rtd_1">E101-T</option>-->
<!--                                <option value="rtd_2">D101A-T</option>-->
<!--                                <option value="rtd_3">D101B-T</option>-->
<!--                                <option value="rtd_4">E201-T</option>-->
<!--                                <option value="rtd_5">GLV-Top-T</option>-->
<!--                                <option value="rtd_6">GLV-Mid-T</option>-->
<!--                                <option value="rtd_7">GLV-BTM-T</option>-->
<!--                                <option value="rtd_8">GLV-EVP-T</option>-->
<!--                                <option value="rtd_9">SettlingA-T</option>-->
<!--                                <option value="rtd_10">SettlingB-T</option>-->
<!--                                <option value="rtd_11">SettlingC-T</option>-->
<!--                                <option value="rtd_12">HotWater-T</option>-->
<!--                                <option value="rtd_13">D402A-T</option>-->
<!--                                <option value="rtd_14">D402B-T</option>-->
<!--                                <option value="rtd_15">D402C-T</option>-->
<!--                                <option value="rtd_16">D402D-T</option>-->
<!--                                <option value="rtd_17">Trans-EVP-T</option>-->
<!--                                <option value="rtd_18">Blue-T</option>-->
<!--                                <option value="rtd_19">Green-T</option>-->
<!--                                <option value="rtd_20">Old Green-T</option>-->
<!--                                <option value="rtd_21">E601-T</option>-->
<!--                                <option value="rtd_22">T601-Top-T</option>-->
<!--                                <option value="rtd_23">T601-Mid-T</option>-->
<!--                                <option value="rtd_24">T601-BTM-T</option>-->
<!--                                <option value="rtd_25">E501-T</option>-->
<!--                                <option value="rtd_26">D501-T</option>-->
<!--                                <option value="rtd_27">T501-Top-T</option>-->
<!--                                <option value="rtd_28">T501-Mid-T</option>-->
<!--                                <option value="rtd_29">T501-BTM-T</option>-->
<!--                                <option value="rtd_30">T502-Mid-T</option>-->
<!--                                <option value="rtd_31">T502-BTM-T</option>-->
<!--&lt;!&ndash;                                <option value="rtd_32">PPRA-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_33">PPRB-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_34">GST T1-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_35">Trans-React-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_36">Bio Storage-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_37">Bio Transfer-T</option>&ndash;&gt;-->
<!--                                <option value="dpl_1">D501-L</option>-->
<!--                                <option value="dpl_2">E401-L</option>-->
<!--                                <option value="dpl_3">T601-L</option>-->
<!--                                <option value="dpl_4">D503-L</option>-->
<!--                                <option value="dpl_5">D504-L</option>-->
<!--                                <option value="dpl_6">T501-L</option>-->
<!--                                <option value="dpl_7">T502-L</option>-->
<!--                                <option value="fm_1">FM 1</option>-->
<!--                                <option value="fm_2">FM 2</option>-->
<!--                                <option value="fm_3">FM 3</option>-->
<!--                                <option value="fm_4">FM 4</option>-->
<!--                                <option value="fm_5">FM 5</option>-->
<!--                                <option value="fm_6">FM 6</option>-->
<!--                                <option value="fm_7">FM 7</option>-->
<!--                                <option value="fm_8">FM 8</option>-->
<!--                                <option value="fm_9">FM 9</option>-->
<!--                                <option value="fm_10">FM 10</option>-->
<!--                                <option value="fm_11">FM 11</option>-->
<!--                                <option value="fm_12">FM 12</option>-->
<!--                                <option value="fm_13">FM 13</option>-->
<!--                                <option value="fm_14">FM 14</option>-->
<!--                                <option value="fm_15">FM 15</option>-->
<!--                                <option value="fm_16">FM 16</option>-->
<!--                                <option value="fm_17">FM 17</option>-->
<!--                                <option value="fm_18">FM 18</option>-->
<!--                                <option value="fm_19">FM 19</option>-->
<!--                                <option value="fm_20">FM 20</option>-->
<!--                                <option value="fm_21">FM 21</option>-->
<!--                                <option value="fm_22">FM 22</option>-->
<!--                                <option value="fm_23">FM 23</option>-->
<!--                                <option value="fm_24">FM 24</option>-->
<!--                                <option value="fm_25">FM 25</option>-->
<!--                                <option value="fm_26">FM 26</option>-->
<!--                                <option value="fm_27">FM 27</option>-->
<!--                                <option value="pt_1">PT 1</option>-->
<!--                                <option value="pt_2">PT 2</option>-->
<!--                                <option value="pt_3">PT 3</option>-->
<!--                                <option value="pt_4">PT 4</option>-->
<!--                                <option value="pt_5">PT 5</option>-->
<!--                                <option value="vg_1">VG 1</option>-->
<!--                                <option value="vg_2">VG 2</option>-->
<!--                                <option value="vg_3">VG 3</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                    </td>-->
<!--                    <td class="col-sm-2">-->
<!--                        <div class="form-group">-->
<!--                            <label>Select 3</label>-->
<!--                            <select v-model="fields.val_3" class="form-control" :disabled="disable">-->
<!--                                <option value="rdl_1">D101A-L</option>-->
<!--                                <option value="rdl_2">D101B-L</option>-->
<!--                                <option value="rdl_3">D405A-L</option>-->
<!--                                <option value="rdl_4">D405B-L</option>-->
<!--                                <option value="rdl_5">D405C-L</option>-->
<!--                                <option value="rdl_6">C401A-L</option>-->
<!--                                <option value="rdl_7">C401B-L</option>-->
<!--                                <option value="rdl_8">D402A-L</option>-->
<!--                                <option value="rdl_9">D402B-L</option>-->
<!--                                <option value="rdl_10">D402C-L</option>-->
<!--                                <option value="rdl_11">D402D-L</option>-->
<!--                                <option value="rdl_12">GLV-L</option>-->
<!--                                <option value="rdl_13">SettlingA-L</option>-->
<!--                                <option value="rdl_14">SettlingB-L</option>-->
<!--                                <option value="rdl_15">SettlingC-L</option>-->
<!--                                <option value="rdl_16">Methanol T1-L</option>-->
<!--                                <option value="rdl_17">Tar-L</option>-->
<!--                                <option value="rdl_18">GST T1-L</option>-->
<!--                                <option value="rdl_19">Methanol T2-L</option>-->
<!--                                <option value="rdl_20">SP1-L</option>-->
<!--                                <option value="rdl_21">SP2-L</option>-->
<!--                                <option value="rdl_22">SP3-L</option>-->
<!--                                <option value="rdl_23">PPRA-L</option>-->
<!--                                <option value="rdl_24">PPRB-L</option>-->
<!--                                <option value="rdl_25">H2SO4-L</option>-->
<!--                                <option value="rtd_1">E101-T</option>-->
<!--                                <option value="rtd_2">D101A-T</option>-->
<!--                                <option value="rtd_3">D101B-T</option>-->
<!--                                <option value="rtd_4">E201-T</option>-->
<!--                                <option value="rtd_5">GLV-Top-T</option>-->
<!--                                <option value="rtd_6">GLV-Mid-T</option>-->
<!--                                <option value="rtd_7">GLV-BTM-T</option>-->
<!--                                <option value="rtd_8">GLV-EVP-T</option>-->
<!--                                <option value="rtd_9">SettlingA-T</option>-->
<!--                                <option value="rtd_10">SettlingB-T</option>-->
<!--                                <option value="rtd_11">SettlingC-T</option>-->
<!--                                <option value="rtd_12">HotWater-T</option>-->
<!--                                <option value="rtd_13">D402A-T</option>-->
<!--                                <option value="rtd_14">D402B-T</option>-->
<!--                                <option value="rtd_15">D402C-T</option>-->
<!--                                <option value="rtd_16">D402D-T</option>-->
<!--                                <option value="rtd_17">Trans-EVP-T</option>-->
<!--                                <option value="rtd_18">Blue-T</option>-->
<!--                                <option value="rtd_19">Green-T</option>-->
<!--                                <option value="rtd_20">Old Green-T</option>-->
<!--                                <option value="rtd_21">E601-T</option>-->
<!--                                <option value="rtd_22">T601-Top-T</option>-->
<!--                                <option value="rtd_23">T601-Mid-T</option>-->
<!--                                <option value="rtd_24">T601-BTM-T</option>-->
<!--                                <option value="rtd_25">E501-T</option>-->
<!--                                <option value="rtd_26">D501-T</option>-->
<!--                                <option value="rtd_27">T501-Top-T</option>-->
<!--                                <option value="rtd_28">T501-Mid-T</option>-->
<!--                                <option value="rtd_29">T501-BTM-T</option>-->
<!--                                <option value="rtd_30">T502-Mid-T</option>-->
<!--                                <option value="rtd_31">T502-BTM-T</option>-->
<!--&lt;!&ndash;                                <option value="rtd_32">PPRA-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_33">PPRB-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_34">GST T1-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_35">Trans-React-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_36">Bio Storage-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_37">Bio Transfer-T</option>&ndash;&gt;-->
<!--                                <option value="dpl_1">D501-L</option>-->
<!--                                <option value="dpl_2">E401-L</option>-->
<!--                                <option value="dpl_3">T601-L</option>-->
<!--                                <option value="dpl_4">D503-L</option>-->
<!--                                <option value="dpl_5">D504-L</option>-->
<!--                                <option value="dpl_6">T501-L</option>-->
<!--                                <option value="dpl_7">T502-L</option>-->
<!--                                <option value="fm_1">FM 1</option>-->
<!--                                <option value="fm_2">FM 2</option>-->
<!--                                <option value="fm_3">FM 3</option>-->
<!--                                <option value="fm_4">FM 4</option>-->
<!--                                <option value="fm_5">FM 5</option>-->
<!--                                <option value="fm_6">FM 6</option>-->
<!--                                <option value="fm_7">FM 7</option>-->
<!--                                <option value="fm_8">FM 8</option>-->
<!--                                <option value="fm_9">FM 9</option>-->
<!--                                <option value="fm_10">FM 10</option>-->
<!--                                <option value="fm_11">FM 11</option>-->
<!--                                <option value="fm_12">FM 12</option>-->
<!--                                <option value="fm_13">FM 13</option>-->
<!--                                <option value="fm_14">FM 14</option>-->
<!--                                <option value="fm_15">FM 15</option>-->
<!--                                <option value="fm_16">FM 16</option>-->
<!--                                <option value="fm_17">FM 17</option>-->
<!--                                <option value="fm_18">FM 18</option>-->
<!--                                <option value="fm_19">FM 19</option>-->
<!--                                <option value="fm_20">FM 20</option>-->
<!--                                <option value="fm_21">FM 21</option>-->
<!--                                <option value="fm_22">FM 22</option>-->
<!--                                <option value="fm_23">FM 23</option>-->
<!--                                <option value="fm_24">FM 24</option>-->
<!--                                <option value="fm_25">FM 25</option>-->
<!--                                <option value="fm_26">FM 26</option>-->
<!--                                <option value="fm_27">FM 27</option>-->
<!--                                <option value="pt_1">PT 1</option>-->
<!--                                <option value="pt_2">PT 2</option>-->
<!--                                <option value="pt_3">PT 3</option>-->
<!--                                <option value="pt_4">PT 4</option>-->
<!--                                <option value="pt_5">PT 5</option>-->
<!--                                <option value="vg_1">VG 1</option>-->
<!--                                <option value="vg_2">VG 2</option>-->
<!--                                <option value="vg_3">VG 3</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                    </td>-->
<!--                    <td class="col-sm-2">-->
<!--                        <div class="form-group">-->
<!--                            <label>Select 4</label>-->
<!--                            <select v-model="fields.val_4" class="form-control" :disabled="disable">-->
<!--                                <option value="rdl_1">D101A-L</option>-->
<!--                                <option value="rdl_2">D101B-L</option>-->
<!--                                <option value="rdl_3">D405A-L</option>-->
<!--                                <option value="rdl_4">D405B-L</option>-->
<!--                                <option value="rdl_5">D405C-L</option>-->
<!--                                <option value="rdl_6">C401A-L</option>-->
<!--                                <option value="rdl_7">C401B-L</option>-->
<!--                                <option value="rdl_8">D402A-L</option>-->
<!--                                <option value="rdl_9">D402B-L</option>-->
<!--                                <option value="rdl_10">D402C-L</option>-->
<!--                                <option value="rdl_11">D402D-L</option>-->
<!--                                <option value="rdl_12">GLV-L</option>-->
<!--                                <option value="rdl_13">SettlingA-L</option>-->
<!--                                <option value="rdl_14">SettlingB-L</option>-->
<!--                                <option value="rdl_15">SettlingC-L</option>-->
<!--                                <option value="rdl_16">Methanol T1-L</option>-->
<!--                                <option value="rdl_17">Tar-L</option>-->
<!--                                <option value="rdl_18">GST T1-L</option>-->
<!--                                <option value="rdl_19">Methanol T2-L</option>-->
<!--                                <option value="rdl_20">SP1-L</option>-->
<!--                                <option value="rdl_21">SP2-L</option>-->
<!--                                <option value="rdl_22">SP3-L</option>-->
<!--                                <option value="rdl_23">PPRA-L</option>-->
<!--                                <option value="rdl_24">PPRB-L</option>-->
<!--                                <option value="rdl_25">H2SO4-L</option>-->
<!--                                <option value="rtd_1">E101-T</option>-->
<!--                                <option value="rtd_2">D101A-T</option>-->
<!--                                <option value="rtd_3">D101B-T</option>-->
<!--                                <option value="rtd_4">E201-T</option>-->
<!--                                <option value="rtd_5">GLV-Top-T</option>-->
<!--                                <option value="rtd_6">GLV-Mid-T</option>-->
<!--                                <option value="rtd_7">GLV-BTM-T</option>-->
<!--                                <option value="rtd_8">GLV-EVP-T</option>-->
<!--                                <option value="rtd_9">SettlingA-T</option>-->
<!--                                <option value="rtd_10">SettlingB-T</option>-->
<!--                                <option value="rtd_11">SettlingC-T</option>-->
<!--                                <option value="rtd_12">HotWater-T</option>-->
<!--                                <option value="rtd_13">D402A-T</option>-->
<!--                                <option value="rtd_14">D402B-T</option>-->
<!--                                <option value="rtd_15">D402C-T</option>-->
<!--                                <option value="rtd_16">D402D-T</option>-->
<!--                                <option value="rtd_17">Trans-EVP-T</option>-->
<!--                                <option value="rtd_18">Blue-T</option>-->
<!--                                <option value="rtd_19">Green-T</option>-->
<!--                                <option value="rtd_20">Old Green-T</option>-->
<!--                                <option value="rtd_21">E601-T</option>-->
<!--                                <option value="rtd_22">T601-Top-T</option>-->
<!--                                <option value="rtd_23">T601-Mid-T</option>-->
<!--                                <option value="rtd_24">T601-BTM-T</option>-->
<!--                                <option value="rtd_25">E501-T</option>-->
<!--                                <option value="rtd_26">D501-T</option>-->
<!--                                <option value="rtd_27">T501-Top-T</option>-->
<!--                                <option value="rtd_28">T501-Mid-T</option>-->
<!--                                <option value="rtd_29">T501-BTM-T</option>-->
<!--                                <option value="rtd_30">T502-Mid-T</option>-->
<!--                                <option value="rtd_31">T502-BTM-T</option>-->
<!--&lt;!&ndash;                                <option value="rtd_32">PPRA-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_33">PPRB-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_34">GST T1-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_35">Trans-React-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_36">Bio Storage-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_37">Bio Transfer-T</option>&ndash;&gt;-->
<!--                                <option value="dpl_1">D501-L</option>-->
<!--                                <option value="dpl_2">E401-L</option>-->
<!--                                <option value="dpl_3">T601-L</option>-->
<!--                                <option value="dpl_4">D503-L</option>-->
<!--                                <option value="dpl_5">D504-L</option>-->
<!--                                <option value="dpl_6">T501-L</option>-->
<!--                                <option value="dpl_7">T502-L</option>-->
<!--                                <option value="fm_1">FM 1</option>-->
<!--                                <option value="fm_2">FM 2</option>-->
<!--                                <option value="fm_3">FM 3</option>-->
<!--                                <option value="fm_4">FM 4</option>-->
<!--                                <option value="fm_5">FM 5</option>-->
<!--                                <option value="fm_6">FM 6</option>-->
<!--                                <option value="fm_7">FM 7</option>-->
<!--                                <option value="fm_8">FM 8</option>-->
<!--                                <option value="fm_9">FM 9</option>-->
<!--                                <option value="fm_10">FM 10</option>-->
<!--                                <option value="fm_11">FM 11</option>-->
<!--                                <option value="fm_12">FM 12</option>-->
<!--                                <option value="fm_13">FM 13</option>-->
<!--                                <option value="fm_14">FM 14</option>-->
<!--                                <option value="fm_15">FM 15</option>-->
<!--                                <option value="fm_16">FM 16</option>-->
<!--                                <option value="fm_17">FM 17</option>-->
<!--                                <option value="fm_18">FM 18</option>-->
<!--                                <option value="fm_19">FM 19</option>-->
<!--                                <option value="fm_20">FM 20</option>-->
<!--                                <option value="fm_21">FM 21</option>-->
<!--                                <option value="fm_22">FM 22</option>-->
<!--                                <option value="fm_23">FM 23</option>-->
<!--                                <option value="fm_24">FM 24</option>-->
<!--                                <option value="fm_25">FM 25</option>-->
<!--                                <option value="fm_26">FM 26</option>-->
<!--                                <option value="fm_27">FM 27</option>-->
<!--                                <option value="pt_1">PT 1</option>-->
<!--                                <option value="pt_2">PT 2</option>-->
<!--                                <option value="pt_3">PT 3</option>-->
<!--                                <option value="pt_4">PT 4</option>-->
<!--                                <option value="pt_5">PT 5</option>-->
<!--                                <option value="vg_1">VG 1</option>-->
<!--                                <option value="vg_2">VG 2</option>-->
<!--                                <option value="vg_3">VG 3</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                    </td>-->
<!--                    <td class="col-sm-2">-->
<!--                        <div class="form-group">-->
<!--                            <label>Select 5</label>-->
<!--                            <select v-model="fields.val_5" class="form-control" :disabled="disable">-->
<!--                                <option value="rdl_1">D101A-L</option>-->
<!--                                <option value="rdl_2">D101B-L</option>-->
<!--                                <option value="rdl_3">D405A-L</option>-->
<!--                                <option value="rdl_4">D405B-L</option>-->
<!--                                <option value="rdl_5">D405C-L</option>-->
<!--                                <option value="rdl_6">C401A-L</option>-->
<!--                                <option value="rdl_7">C401B-L</option>-->
<!--                                <option value="rdl_8">D402A-L</option>-->
<!--                                <option value="rdl_9">D402B-L</option>-->
<!--                                <option value="rdl_10">D402C-L</option>-->
<!--                                <option value="rdl_11">D402D-L</option>-->
<!--                                <option value="rdl_12">GLV-L</option>-->
<!--                                <option value="rdl_13">SettlingA-L</option>-->
<!--                                <option value="rdl_14">SettlingB-L</option>-->
<!--                                <option value="rdl_15">SettlingC-L</option>-->
<!--                                <option value="rdl_16">Methanol T1-L</option>-->
<!--                                <option value="rdl_17">Tar-L</option>-->
<!--                                <option value="rdl_18">GST T1-L</option>-->
<!--                                <option value="rdl_19">Methanol T2-L</option>-->
<!--                                <option value="rdl_20">SP1-L</option>-->
<!--                                <option value="rdl_21">SP2-L</option>-->
<!--                                <option value="rdl_22">SP3-L</option>-->
<!--                                <option value="rdl_23">PPRA-L</option>-->
<!--                                <option value="rdl_24">PPRB-L</option>-->
<!--                                <option value="rdl_25">H2SO4-L</option>-->
<!--                                <option value="rtd_1">E101-T</option>-->
<!--                                <option value="rtd_2">D101A-T</option>-->
<!--                                <option value="rtd_3">D101B-T</option>-->
<!--                                <option value="rtd_4">E201-T</option>-->
<!--                                <option value="rtd_5">GLV-Top-T</option>-->
<!--                                <option value="rtd_6">GLV-Mid-T</option>-->
<!--                                <option value="rtd_7">GLV-BTM-T</option>-->
<!--                                <option value="rtd_8">GLV-EVP-T</option>-->
<!--                                <option value="rtd_9">SettlingA-T</option>-->
<!--                                <option value="rtd_10">SettlingB-T</option>-->
<!--                                <option value="rtd_11">SettlingC-T</option>-->
<!--                                <option value="rtd_12">HotWater-T</option>-->
<!--                                <option value="rtd_13">D402A-T</option>-->
<!--                                <option value="rtd_14">D402B-T</option>-->
<!--                                <option value="rtd_15">D402C-T</option>-->
<!--                                <option value="rtd_16">D402D-T</option>-->
<!--                                <option value="rtd_17">Trans-EVP-T</option>-->
<!--                                <option value="rtd_18">Blue-T</option>-->
<!--                                <option value="rtd_19">Green-T</option>-->
<!--                                <option value="rtd_20">Old Green-T</option>-->
<!--                                <option value="rtd_21">E601-T</option>-->
<!--                                <option value="rtd_22">T601-Top-T</option>-->
<!--                                <option value="rtd_23">T601-Mid-T</option>-->
<!--                                <option value="rtd_24">T601-BTM-T</option>-->
<!--                                <option value="rtd_25">E501-T</option>-->
<!--                                <option value="rtd_26">D501-T</option>-->
<!--                                <option value="rtd_27">T501-Top-T</option>-->
<!--                                <option value="rtd_28">T501-Mid-T</option>-->
<!--                                <option value="rtd_29">T501-BTM-T</option>-->
<!--                                <option value="rtd_30">T502-Mid-T</option>-->
<!--                                <option value="rtd_31">T502-BTM-T</option>-->
<!--&lt;!&ndash;                                <option value="rtd_32">PPRA-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_33">PPRB-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_34">GST T1-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_35">Trans-React-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_36">Bio Storage-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_37">Bio Transfer-T</option>&ndash;&gt;-->
<!--                                <option value="dpl_1">D501-L</option>-->
<!--                                <option value="dpl_2">E401-L</option>-->
<!--                                <option value="dpl_3">T601-L</option>-->
<!--                                <option value="dpl_4">D503-L</option>-->
<!--                                <option value="dpl_5">D504-L</option>-->
<!--                                <option value="dpl_6">T501-L</option>-->
<!--                                <option value="dpl_7">T502-L</option>-->
<!--                                <option value="fm_1">FM 1</option>-->
<!--                                <option value="fm_2">FM 2</option>-->
<!--                                <option value="fm_3">FM 3</option>-->
<!--                                <option value="fm_4">FM 4</option>-->
<!--                                <option value="fm_5">FM 5</option>-->
<!--                                <option value="fm_6">FM 6</option>-->
<!--                                <option value="fm_7">FM 7</option>-->
<!--                                <option value="fm_8">FM 8</option>-->
<!--                                <option value="fm_9">FM 9</option>-->
<!--                                <option value="fm_10">FM 10</option>-->
<!--                                <option value="fm_11">FM 11</option>-->
<!--                                <option value="fm_12">FM 12</option>-->
<!--                                <option value="fm_13">FM 13</option>-->
<!--                                <option value="fm_14">FM 14</option>-->
<!--                                <option value="fm_15">FM 15</option>-->
<!--                                <option value="fm_16">FM 16</option>-->
<!--                                <option value="fm_17">FM 17</option>-->
<!--                                <option value="fm_18">FM 18</option>-->
<!--                                <option value="fm_19">FM 19</option>-->
<!--                                <option value="fm_20">FM 20</option>-->
<!--                                <option value="fm_21">FM 21</option>-->
<!--                                <option value="fm_22">FM 22</option>-->
<!--                                <option value="fm_23">FM 23</option>-->
<!--                                <option value="fm_24">FM 24</option>-->
<!--                                <option value="fm_25">FM 25</option>-->
<!--                                <option value="fm_26">FM 26</option>-->
<!--                                <option value="fm_27">FM 27</option>-->
<!--                                <option value="pt_1">PT 1</option>-->
<!--                                <option value="pt_2">PT 2</option>-->
<!--                                <option value="pt_3">PT 3</option>-->
<!--                                <option value="pt_4">PT 4</option>-->
<!--                                <option value="pt_5">PT 5</option>-->
<!--                                <option value="vg_1">VG 1</option>-->
<!--                                <option value="vg_2">VG 2</option>-->
<!--                                <option value="vg_3">VG 3</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                    </td>-->
<!--                    <td class="col-sm-2">-->
<!--                        <div class="form-group">-->
<!--                            <label>Select 6</label>-->
<!--                            <select v-model="fields.val_6" class="form-control" :disabled="disable">-->
<!--                                <option value="rdl_1">D101A-L</option>-->
<!--                                <option value="rdl_2">D101B-L</option>-->
<!--                                <option value="rdl_3">D405A-L</option>-->
<!--                                <option value="rdl_4">D405B-L</option>-->
<!--                                <option value="rdl_5">D405C-L</option>-->
<!--                                <option value="rdl_6">C401A-L</option>-->
<!--                                <option value="rdl_7">C401B-L</option>-->
<!--                                <option value="rdl_8">D402A-L</option>-->
<!--                                <option value="rdl_9">D402B-L</option>-->
<!--                                <option value="rdl_10">D402C-L</option>-->
<!--                                <option value="rdl_11">D402D-L</option>-->
<!--                                <option value="rdl_12">GLV-L</option>-->
<!--                                <option value="rdl_13">SettlingA-L</option>-->
<!--                                <option value="rdl_14">SettlingB-L</option>-->
<!--                                <option value="rdl_15">SettlingC-L</option>-->
<!--                                <option value="rdl_16">Methanol T1-L</option>-->
<!--                                <option value="rdl_17">Tar-L</option>-->
<!--                                <option value="rdl_18">GST T1-L</option>-->
<!--                                <option value="rdl_19">Methanol T2-L</option>-->
<!--                                <option value="rdl_20">SP1-L</option>-->
<!--                                <option value="rdl_21">SP2-L</option>-->
<!--                                <option value="rdl_22">SP3-L</option>-->
<!--                                <option value="rdl_23">PPRA-L</option>-->
<!--                                <option value="rdl_24">PPRB-L</option>-->
<!--                                <option value="rdl_25">H2SO4-L</option>-->
<!--                                <option value="rtd_1">E101-T</option>-->
<!--                                <option value="rtd_2">D101A-T</option>-->
<!--                                <option value="rtd_3">D101B-T</option>-->
<!--                                <option value="rtd_4">E201-T</option>-->
<!--                                <option value="rtd_5">GLV-Top-T</option>-->
<!--                                <option value="rtd_6">GLV-Mid-T</option>-->
<!--                                <option value="rtd_7">GLV-BTM-T</option>-->
<!--                                <option value="rtd_8">GLV-EVP-T</option>-->
<!--                                <option value="rtd_9">SettlingA-T</option>-->
<!--                                <option value="rtd_10">SettlingB-T</option>-->
<!--                                <option value="rtd_11">SettlingC-T</option>-->
<!--                                <option value="rtd_12">HotWater-T</option>-->
<!--                                <option value="rtd_13">D402A-T</option>-->
<!--                                <option value="rtd_14">D402B-T</option>-->
<!--                                <option value="rtd_15">D402C-T</option>-->
<!--                                <option value="rtd_16">D402D-T</option>-->
<!--                                <option value="rtd_17">Trans-EVP-T</option>-->
<!--                                <option value="rtd_18">Blue-T</option>-->
<!--                                <option value="rtd_19">Green-T</option>-->
<!--                                <option value="rtd_20">Old Green-T</option>-->
<!--                                <option value="rtd_21">E601-T</option>-->
<!--                                <option value="rtd_22">T601-Top-T</option>-->
<!--                                <option value="rtd_23">T601-Mid-T</option>-->
<!--                                <option value="rtd_24">T601-BTM-T</option>-->
<!--                                <option value="rtd_25">E501-T</option>-->
<!--                                <option value="rtd_26">D501-T</option>-->
<!--                                <option value="rtd_27">T501-Top-T</option>-->
<!--                                <option value="rtd_28">T501-Mid-T</option>-->
<!--                                <option value="rtd_29">T501-BTM-T</option>-->
<!--                                <option value="rtd_30">T502-Mid-T</option>-->
<!--                                <option value="rtd_31">T502-BTM-T</option>-->
<!--&lt;!&ndash;                                <option value="rtd_32">PPRA-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_33">PPRB-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_34">GST T1-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_35">Trans-React-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_36">Bio Storage-T</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option value="rtd_37">Bio Transfer-T</option>&ndash;&gt;-->
<!--                                <option value="dpl_1">D501-L</option>-->
<!--                                <option value="dpl_2">E401-L</option>-->
<!--                                <option value="dpl_3">T601-L</option>-->
<!--                                <option value="dpl_4">D503-L</option>-->
<!--                                <option value="dpl_5">D504-L</option>-->
<!--                                <option value="dpl_6">T501-L</option>-->
<!--                                <option value="dpl_7">T502-L</option>-->
<!--                                <option value="fm_1">FM 1</option>-->
<!--                                <option value="fm_2">FM 2</option>-->
<!--                                <option value="fm_3">FM 3</option>-->
<!--                                <option value="fm_4">FM 4</option>-->
<!--                                <option value="fm_5">FM 5</option>-->
<!--                                <option value="fm_6">FM 6</option>-->
<!--                                <option value="fm_7">FM 7</option>-->
<!--                                <option value="fm_8">FM 8</option>-->
<!--                                <option value="fm_9">FM 9</option>-->
<!--                                <option value="fm_10">FM 10</option>-->
<!--                                <option value="fm_11">FM 11</option>-->
<!--                                <option value="fm_12">FM 12</option>-->
<!--                                <option value="fm_13">FM 13</option>-->
<!--                                <option value="fm_14">FM 14</option>-->
<!--                                <option value="fm_15">FM 15</option>-->
<!--                                <option value="fm_16">FM 16</option>-->
<!--                                <option value="fm_17">FM 17</option>-->
<!--                                <option value="fm_18">FM 18</option>-->
<!--                                <option value="fm_19">FM 19</option>-->
<!--                                <option value="fm_20">FM 20</option>-->
<!--                                <option value="fm_21">FM 21</option>-->
<!--                                <option value="fm_22">FM 22</option>-->
<!--                                <option value="fm_23">FM 23</option>-->
<!--                                <option value="fm_24">FM 24</option>-->
<!--                                <option value="fm_25">FM 25</option>-->
<!--                                <option value="fm_26">FM 26</option>-->
<!--                                <option value="fm_27">FM 27</option>-->
<!--                                <option value="pt_1">PT 1</option>-->
<!--                                <option value="pt_2">PT 2</option>-->
<!--                                <option value="pt_3">PT 3</option>-->
<!--                                <option value="pt_4">PT 4</option>-->
<!--                                <option value="pt_5">PT 5</option>-->
<!--                                <option value="vg_1">VG 1</option>-->
<!--                                <option value="vg_2">VG 2</option>-->
<!--                                <option value="vg_3">VG 3</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                    </td>-->
<!--                </tr>-->
